import fs from "fs";
import path from "path";

const newsDirectory = path.join(process.cwd(), "content/news");
const outputDirectory = path.join(process.cwd(), "src/lib/generated");
const outputFile = path.join(outputDirectory, "news.ts");

function escapeTemplateLiteral(value) {
  return value.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

if (!fs.existsSync(newsDirectory)) {
  fs.mkdirSync(outputDirectory, { recursive: true });
  fs.writeFileSync(
    outputFile,
    `// Auto-generated by scripts/generate-news.mjs\nexport const newsRawFiles: Record<string, string> = {};\n`,
  );
  process.exit(0);
}

const newsRawFiles = Object.fromEntries(
  fs
    .readdirSync(newsDirectory)
    .filter((filename) => filename.endsWith(".md"))
    .map((filename) => {
      const slug = filename.replace(/\.md$/, "");
      const raw = fs.readFileSync(path.join(newsDirectory, filename), "utf8");
      return [slug, raw];
    }),
);

const fileContents = `// Auto-generated by scripts/generate-news.mjs
export const newsRawFiles: Record<string, string> = {
${Object.entries(newsRawFiles)
  .map(([slug, raw]) => `  ${JSON.stringify(slug)}: \`${escapeTemplateLiteral(raw)}\`,`)
  .join("\n")}
};
`;

fs.mkdirSync(outputDirectory, { recursive: true });
fs.writeFileSync(outputFile, fileContents);

console.log(`Generated ${outputFile} with ${Object.keys(newsRawFiles).length} news item(s).`);
